references:
  defaults: &defaults
    working_directory: ~/bigtest
    docker:
      - image: circleci/node:8-browsers

  add_ssh_keys: &add_ssh_keys

  cache_key: &cache_key
    interactor-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/bigtest

version: 2.0
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: *cache_key
      - run:
          name: Install dependencies
          command: yarn
      - persist_to_workspace:
          root: ./
          paths:
            - ./
      - save_cache:
          name: Save cache
          key: *cache_key
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Lint packages
          command: yarn lint

  build:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build documentation
          command: yarn docs
      - run:
          name: Build packages
          command: yarn build

  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: yarn test

  deploy:
    <<: *defaults
    steps:
      - *attach_workspace
      - add_ssh_keys:
          fingerprints:
            - 2e:3e:1e:98:92:42:17:a6:ee:23:fb:d6:cb:cc:42:5e
      - run:
          name: Setup NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: yarn bigtest-release --access=public
      - run:
          name: Push Tags
          command: git push --tags

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - lint
            - build
            - test
          filters:
            branches:
              only: master
