on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Node 12
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn build
      - run: yarn workspace @bigtest/cli run test
      - run: yarn workspace @bigtest/convergence run test
      - run: xvfb-run yarn workspace @bigtest/interactor run --browser chrome